name: chetna_app
description: "AI-Powered Safety and Wellness Monitor"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.13.1

  # Communication & Emergency
  telephony: ^0.2.0
  vibration: ^3.1.5
  geolocator: ^14.0.2
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.0.0

  # UI & Visualization
  table_calendar: ^3.0.9
  syncfusion_flutter_charts: ^32.1.19
  flutter_animation_progress_bar: ^2.0.0
  avatar_glow: ^2.0.2   # ADDED: Required for the Voice Guardian pulse animation

  # Firebase
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  firebase_database: ^11.1.2

  # Sensors & Environment Monitoring
  sensors_plus: ^7.0.0
  light: ^4.1.0
  noise_meter: ^5.1.0
  connectivity_plus: ^6.1.0

  # Background & Storage
  flutter_background: ^1.3.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0

  # AI / ML
  tflite_flutter: ^0.12.0

  # Audio & Voice
  speech_to_text: ^7.0.0  # For voice recognition
  audioplayers: ^6.0.0    # For playing audio
  audio_session: ^0.2.2   # For audio session management
  just_audio: ^0.10.0     # For recording and playing audio
  
  # Recording
  record: ^6.1.2  # Added for audio recording

  # Permissions
  permission_handler: ^12.0.1

  # Utilities
  rxdart: ^0.27.7
  http: ^1.1.0

  device_info_plus: ^9.0.0

  flutter_animator: ^3.1.2
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # TensorFlow Lite models
    - assets/models/fall_model.tflite
    - assets/models/wellness_diagnostic.tflite

    # Audio files
    - assets/audio/siren.mp3
    - assets/audio/white_noise.mp3
    - assets/audio/trusted_voice_message.mp3

    - assets/icon/app_icon.jpeg

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/app_icon.jpeg"
  min_sdk_android: 21